Hospital/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.views.i18n import JavaScriptCatalog

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('doctors.urls')), 
    path('jsi18n', JavaScriptCatalog.as_view(), name='js-catlog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

doctors/urls.py
from django.urls import path
from . import views

app_name="doctors"
urlpatterns = [
    path('', views.index, name="index"),
    path('about', views.about, name="about"),
    path('maps', views.maps, name="maps"),
    path('project_requirement', views.project_requirement, name="project_requirement"),


#NEW
    path('news', views.news, name="news"),
    path('news/<pk>', views.news_content, name="news_content"),
    path('deleteNews/<pk>', views.deleteNews, name="deleteNews"),
    path('addnews', views.addNews, name="addNews"),
    path('updatenews/<pk>', views.updateNew, name="updateNew"),


#ARTICLE
    path('healthblog', views.healthblog, name="healthblog"),
    path('healthblog/<pk>', views.healthblog_content, name="healthblog_content"),
    path('deletehealthblog/<pk>', views.deleteArticle, name="deleteArticle"),
    path('addhealthblog', views.addArticle, name="addArticle"),
    path('updatehealthblog/<pk>', views.updateArticle, name="updateArticle"),


#PACKAGE
    path('package/', views.package, name="package"),
    path('package/<str:pk>', views.package_content, name="package_content"),
    path('editpackage/<str:pk>', views.editpackage, name="editpackage"),
    path('deletepackage/<str:pk>', views.deletePackage, name="deletepackage"),
    path('addpackage', views.addPackage, name="addPackage"),
    path('buy/<str:pk>', views.buy, name="buy"),
    path('mypack', views.mypack, name="mypack" ),
    path('packbuy', views.packbuy, name="packbuy" ),
    path('packbuy/<str:pk>', views.packbuy_one, name="packbuyone" ),
    path('checkslip/<str:pk>', views.checkslip, name="checkslip" ),
    path('mypack/<str:pk>', views.mypack_one, name="mypackone" ),
    path('sendslip/<str:pk>', views.sendslip, name="sendslip" ),



#Appointment
    path('appointment/<pk>', views.appointment, name="appointment"),
    path('appointmentfordoc/<pk>', views.adminAppointment_one, name="appointment_one"),
    path('deleteappointment/<pk>', views.deleteAppointment, name="deleteappointment"),
    path('adminappointment', views.adminAppointment, name="mappointment"),
    path('changestatusappointment/<pk>', views.changeStatusAppointment, name="changestatusapp"),
    

    # register, login profile
    path('register/', views.registerPage, name="register"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutPLS, name="logout"),
    path('profile', views.profile, name="profile"),
    path('accsetting', views.account, name="accsetting"),


    path('finddoc', views.finddoc, name="finddoc"),
    path('docprofile/<pk>', views.docprofile, name="docprofile"),
    path('deleteDoc/<pk>', views.deleteDoc, name="deleteDoc"),
    path('spec', views.spec, name="spec"),
    path('addDoc', views.addDoc, name="addDoc"),
    path('updateDoc/<pk>', views.updateDoc, name="updateDoc"),
]

doctors/forms.py
from django import forms
from django.db.models import fields
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.contrib.admin.widgets import  AdminDateWidget, AdminTimeWidget, AdminSplitDateTime
from .models import *

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class CreateArticleForm(ModelForm):
    class Meta:
        model = Article
        fields = ['header', 'doctor', 'context', 'img']


class CreateNewsForm(ModelForm):
    class Meta:
        model = New
        fields = ['header', 'context', 'img']

class accForm(ModelForm):
    class Meta:
        model = Patient
        fields = '__all__'
        exclude = ['user', 'date_created']

class CreatePackageForm(ModelForm):
    class Meta:
        model = Package
        fields = '__all__'
        exclude = ['date_created']
        
class CreateDocForm(ModelForm):
    class Meta:
        model = Doctor
        fields = '__all__'
        exclude = ['date_created']

class StatusBuy(ModelForm):
    class Meta:
        model = Buy
        fields = ['status']

class SendSlip(ModelForm):
    class Meta:
        model = Buy
        fields = ['img']
        

class AppointmentForm(forms.Form):
    symptom = forms.CharField(max_length=100)
    date_input = forms.DateField(widget=AdminDateWidget())

doctors/views.py
from django.shortcuts import render, redirect
from doctors.decorator import *
from doctors.models import *
from .forms import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import Group
import os
from django.contrib import messages
from django.db.models import Q
from datetime import date, datetime
# from django.contrib.admin.widgets import  AdminDateWidget
# Create your views here.


def index(request):
    articles = Article.objects.all()
    news = New.objects.all()
    return render(request, "doctors/index.html", {"articles": articles, "news": news})

def about(request):
    return render(request, "doctors/about.html")

def maps(request):
    return render(request, "doctors/maps.html")

def project_requirement(request):
    return render(request, "doctors/requirement.html")

#-----------------------------------------------------------------------------------

# ARTICLE

def healthblog(request):
    articles = Article.objects.all()
    context = {"articles": articles}
    return render(request, "doctors/healthblog.html", context)

def healthblog_content(request, pk):
    article = Article.objects.filter(id=pk).first()
    context = {"article": article}
    return render(request, "doctors/healthblog_one.html", context)

@admin_only
def deleteArticle(request, pk):
    article = Article.objects.get(id=pk)
    if request.method == "POST":
        article.delete()
        return redirect("doctors:healthblog")

@admin_only
def addArticle(request):
    form = CreateArticleForm()
    if request.method == 'POST':
        form = CreateArticleForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            article = Article.objects.values('id').order_by('-id').first()
            id_last = article['id']
            return redirect("doctors:healthblog_content", pk=id_last)
    return render(request, "doctors/addhealthblog.html", {"form": form})

@admin_only
def updateArticle(request, pk):
    article = Article.objects.get(id=pk)
    form = CreateArticleForm(instance=article)
    if request.method == 'POST':
        createNewsForm = CreateArticleForm(
            request.POST, request.FILES, instance=article)
        if createNewsForm.is_valid():
            createNewsForm.save()
            return redirect("doctors:healthblog_content", pk=pk)
    context = {"form": form, "article": article}
    return render(request, "doctors/updatehealthblog.html", context)

#-----------------------------------------------------------------------------------

# NEW
def news(request):
    news = New.objects.all()
    context = {"news": news}
    return render(request, "doctors/news.html", context)

def news_content(request, pk):
    new = New.objects.filter(id=pk).first()
    context = {"new": new}
    return render(request, "doctors/news_one.html", context)

@admin_only
def deleteNews(request, pk):
    new = New.objects.get(id=pk)
    if request.method == "POST":
        new.delete()
        return redirect("doctors:news")

@admin_only
def addNews(request):
    form = CreateNewsForm()
    if request.method == 'POST':
        createNewsForm = CreateNewsForm(request.POST, request.FILES)
        if createNewsForm.is_valid():
            createNewsForm.save()
            news = New.objects.values('id').order_by('-id').first()
            # id_last = news['id']
            return redirect("doctors:news_content", pk=news['id'])
    return render(request, "doctors/addnews.html", {"form": form})

@admin_only
def updateNew(request, pk):
    new = New.objects.get(id=pk)
    form = CreateNewsForm(instance=new)
    if request.method == 'POST':
        form = CreateNewsForm(request.POST, request.FILES, instance=new)
        if form.is_valid():
            form.save()
            return redirect("doctors:news_content", pk=pk)
    context = {"form": form, "new": new}
    return render(request, "doctors/updatenews.html", context)

#-----------------------------------------------------------------------------------

# PACKAGE


def package(request):
    packages = Package.objects.all()
    return render(request, "doctors/package.html", {"packages": packages})

def package_content(request, pk):
    pack = Package.objects.filter(id=pk).first()
    return render(request, "doctors/package_one.html", {'pack': pack})

@admin_only
def editpackage(request, pk):
    pack = Package.objects.get(id=pk)
    form = CreatePackageForm(instance=pack)
    if request.method == 'POST':
        form = CreatePackageForm(request.POST, request.FILES, instance=pack)
        if form.is_valid():
            form.save()
            return redirect("doctors:package_content", pk=id_last)
    context = {"form": form}
    return render(request, "doctors/editpackage.html", context)

@admin_only
def deletePackage(request, pk):
    pack = Package.objects.get(id=pk)
    pack.delete()
    return redirect("doctors:package")

@admin_only
def addPackage(request):
    form = CreatePackageForm()
    if request.method == 'POST':
        newform = CreatePackageForm(request.POST, request.FILES)
        if newform.is_valid():
            newform.save()
            pack = Package.objects.values('id').order_by('-id').first()
            id_last = pack['id']
            return redirect("doctors:package_content", pk=id_last)
    return render(request, "doctors/addpackage.html", {"form": form})

@login_required(login_url='doctors:login')
def buy(request , pk):
    pack = Package.objects.get(id=pk)
    pat = request.user.patient
    Buy.objects.create(patient=pat, package=pack)
    return redirect("doctors:package")

@admin_only
def packbuy(request):
    buy = Buy.objects.all()
    return render(request, "doctors/packbuy.html", {'buy': buy})


def mypack(request):
    patient = request.user.patient.buy_set.all()
    return render(request, "doctors/mypack.html", {'patient': patient})

@admin_only
def packbuy_one(request, pk):
    buy = Buy.objects.filter(id=pk).first()
    return render(request, "doctors/packbuy_one.html", {'buy': buy} )

@admin_only
def checkslip(request, pk):
    buy = Buy.objects.filter(id=pk).update(status='PAID')
    return redirect("doctors:packbuy")

def mypack_one(request, pk):
    mypack = request.user.patient.buy_set.get(id=pk)
    return render(request, "doctors/mypack_one.html", {'mypack': mypack})

def sendslip(request, pk):
    mypack = request.user.patient.buy_set.get(id=pk)
    form = SendSlip(instance=mypack)
    if request.method == 'POST':
        form = SendSlip(request.POST, request.FILES, instance=mypack)
        if form.is_valid():
            form.save()
            return redirect("doctors:mypack")
    return render(request, "doctors/sendslip.html", {"form": form})

#-----------------------------------------------------------------------------------

# Appointment profile

@login_required(login_url='doctors:login')
def appointment(request, pk):
    doctor = Doctor.objects.filter(id=pk).first()
    form = AppointmentForm()
    date_now = datetime.now()
    if request.method == 'POST':
        symptom_input = request.POST.get("symptom")
        date_input = request.POST.get("date_input")
        if datetime(int(date_input[:4]), int(date_input[5:7]), int(date_input[8:]),) <= date_now:
            messages.add_message(request, messages.SUCCESS, f"ไม่สามารถนัดพบแพทย์ได้ กรุณาเลือกวันให้ถูกต้อง")   #กรณีนัดวันที่ผ่านมาแล้ว
            return redirect("doctors:appointment", pk)
        appointment = Appointment.objects.create(
            Patient_id=request.user.patient,
            Doctor_id=doctor,
            symptom=symptom_input
        )
        appointment.dateapp = date_input
        appointment.save()
        return redirect("doctors:profile")

    context = {"form": form, "doctor": doctor}
    return render(request, "doctors/appointment_patient.html", context)


def deleteAppointment(request, pk):
    appointment = Appointment.objects.get(id=pk)
    appointment.delete()
    return redirect("doctors:profile")

@admin_only
def adminAppointment(request):
    appointment = Appointment.objects.all()
    return render(request, "doctors/mappointment.html", {"appointment": appointment})

def changeStatusAppointment(request, pk):
    app = Appointment.objects.filter(id=pk).update(status='CONFIRM')
    return redirect("doctors:mappointment")

def adminAppointment_one(request, pk):
    doctor = Doctor.objects.get(id=pk)
    appointment = Appointment.objects.filter(Doctor_id=doctor)
    return render(request, "doctors/mappointment.html", {"appointment": appointment})

def profile(request):
    appointment = Appointment.objects.filter(Patient_id=request.user.patient)
    return render(request, "doctors/profile.html", {"appointment": appointment})

#-----------------------------------------------------------------------------------

#register / login / logout

@unauthenticated_user
def registerPage(request):
    form = CreateUserForm()
    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            username = form.cleaned_data.get('username')
            group = Group.objects.get(name='patient')
            user.groups.add(group)
            Patient.objects.create(
                user=user
            )

            messages.success(request, 'Account was created for ' + username)
            return redirect('doctors:login')
    return render(request, 'doctors/register.html', {'form': form})

@unauthenticated_user
def loginPage(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('doctors:index')
        else:

doctors/templates/doctors/addpackage.html
{% extends "doctors/layout.html" %}
{% load static %}

{% block head %}
<link rel="Stylesheet" href="{% static 'css/style-adddoc.css' %}">
{% endblock %}

{% block content %}

<div class="add-doctor-card">
    <div class="header-addhb">
        <h2>Add Package</h2>
    </div>

    <form method="POST" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" name="Create Package" class="btn">
    </form>

</div>
{% endblock %}

doctors/templates/doctors/docprofile.html
{% extends "doctors/layout.html" %}
{% load static %}

{% block head %}
    <link rel="Stylesheet" href="{% static 'css/style-dprofile.css' %}">
{% endblock %}

{% block content %}
<h2 class="dp-header">INFOMATION</h2>
<div class="doctor-card">
    <div class="zone-l">
        <div class="doc-img">
            <img src="{{doctor.profile_pic.url}}" alt="" srcset="">
        </div>

        {% if not request.user.is_superuser %}
        <div class="button-zone">
            <a href="{% url 'doctors:appointment' doctor.id %}" class="app-butt">
                <ion-icon name="calendar"></ion-icon>
                <p>นัดหมายแพทย์</p>
            </a>
        </div>
        {% endif %}

        {% if request.user.is_superuser %}
        <div class="button-zone">
            <a href="{% url 'doctors:appointment_one' doctor.id %}" class="app-butt">  <!-- ฝ่กทำทีนะกชมล -->
                <ion-icon name="person"></ion-icon>
                <p>ผู้ป่วย</p>
            </a>
        </div>
        {% endif %}

    </div>
    <div class="zone-r">
        <div class="name">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
            {% if request.user.is_superuser %}
            <div class="button-group">
                <a href="{% url 'doctors:updateDoc' doctor.id %}">แก้ไข</a>
            <form action= "{% url 'doctors:deleteDoc' doctor.id %}" method="POST">
            {% csrf_token %}
            <button  type="submit" class="remove-button"><h3 class="danger">ลบ</h3></button>
            </div>
            {% endif %}
        </div>

        <div class="xpert">
            <h3>ความชำนาญ</h3>
            <p>{{doctor.spec}}</p>
        </div>

        <div class="lang">
            <h3>ข้อมูลติดต่อ</h3>
            <p>{{doctor.phone}}</p>
            <p>{{doctor.email}}</p>
        </div>


{% endblock %}

doctors/templates/doctors/healthblog_one.html
{% extends "doctors/layout.html" %}
{% load static %}

{% block head %}
    <link rel="Stylesheet" href="{% static 'css/style-editarticle.css' %}">
{% endblock %}

{% block content %}

    <div class="header-news">
        <h2>{{ article.header }}</h2>
    </div>
 
    <img src="{{article.img.url}}" alt="" class="img-blog">

    {% if request.user.is_superuser %} 
    <div class="button-group">
        <a href="{% url 'doctors:updateArticle' article.id %}" class="edit-button"><h3>แก้ไข</h3></a>
        
        <form action= "{% url 'doctors:deleteArticle' article.id %}" method="POST">
            {% csrf_token %}
        <button  type="submit" class="remove-button"><h3>ลบ</h3></button>
    </div>
    {% endif %}
    <p class="content-blog">{{ article.context }}</p>


{% endblock %}

doctors/templates/doctors/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Hospital</title>
        <link rel="Stylesheet" href="{% static 'css/style-navbar.css' %}">
        <link rel="Stylesheet" href="{% static 'css/style-about.css' %}">
        {% block head %}
        {% endblock %}
    </head>
    <body>
        <div id="navbar">
        <div class="nav-box-l">
            <a href="#" class="menu-bars" id="show-menu">
                <ion-icon name="menu-outline"></ion-icon>
            </a>
            <a href="{% url 'doctors:index' %}"><img src="{% static 'images/logo.png' %}"></img></a>
        </div>
        {% if request.user.is_active %}
        <div class="nav-box-r">
            <a href="{% url 'doctors:profile' %}" class="user-profile">
                <img src =" {{request.user.patient.profile_pic.url}}" >
                <p>{{request.user.patient.First_name}}</p> <!-- {{request.user.patient.Last_name}} -->
            </a>

            <div class="normal-a">
            <a href="#" id="show-more" onclick="showMore();">
                <ion-icon name="caret-down"></ion-icon>
            </a>
        </div>
        </div>
        {% else %}
        <div class="nav-box-r">
            <a href="{% url 'doctors:login' %}" class="signin">SIGN IN </a>
            <a href="{% url 'doctors:register' %}"  class="signup">SIGN UP</a>
        </div>
        {% endif %}
    </div>

    <div class="box-head-empty"></div>

    <div class ="area-content" id="area-content">
        {% block content %}
        {% endblock %}
        <script type="text/javascript" src="{% static 'js/app-about.js' %}"></script>
    </div>

    <nav id="nav-menu">
        <ul class="nav-menu-items">
            <div id="navbar-toggle">
                <a href="#" class="menu-bars" id="hide-menu">
                    <ion-icon name="menu-outline"></ion-icon>
                </a>
                <a href="{% url 'doctors:index' %}"><img src="{% static 'images/logo.png' %}"></img></a>
            </div>
            <div class="nav-section">
                {% if request.user.is_superuser %}
                <a class="nav-text" href="{% url 'doctors:index' %}"><li>หน้าแรก</li></a>
                <a class="nav-text" href="{% url 'doctors:about' %}"><li>เกี่ยวกับเรา</li>
                <a class="nav-text" href="{% url 'doctors:healthblog' %}"><li>จัดการบทความ</li></a>
                <a class="nav-text" href="{% url 'doctors:news' %}"><li>จัดการข่าว</li></a>
                <a class="nav-text" href="{% url 'doctors:package' %}"><li>จัดการแพ็คเกจ</li></a>
                <a class="nav-text" href="{% url 'doctors:maps' %}"><li>แผนที่</li></a>
                <a class="nav-text" href="{% url 'doctors:spec' %}"><li>รายชื่อแพทย์</li></a>
                <a class="nav-text" href="{% url 'doctors:mappointment' %}"><li>ข้อมูลการนัดพบแพทย์</li></a>
                <a class="nav-text" href="{% url 'doctors:packbuy' %}"><li>ข้อมูลการซื้อ</li></a>
                {% elif request.user.is_active %}
                <a class="nav-text" href="{% url 'doctors:index' %}"><li>หน้าแรก</li></a>
                <a class="nav-text" href="{% url 'doctors:about' %}"><li>เกี่ยวกับเรา</li></a>
                <a class="nav-text" href="{% url 'doctors:healthblog' %}"><li>บทความทั้งหมด</li></a>
                <a class="nav-text" href="{% url 'doctors:news' %}"><li>ข่าวสาร</li></a>
                <a class="nav-text" href="{% url 'doctors:package' %}"><li>แพ็คเกจ</li></a>
                <a class="nav-text" href="{% url 'doctors:maps' %}"><li>แผนที่</li></a>
                <a class="nav-text" href="{% url 'doctors:spec' %}"><li>รายชื่อแพทย์</li></a>
                {% else %}
                <a class="nav-text" href="{% url 'doctors:index' %}"><li>หน้าแรก</li></a>
                <a class="nav-text" href="{% url 'doctors:about' %}"><li>เกี่ยวกับเรา</li></a>
                <a class="nav-text" href="{% url 'doctors:healthblog' %}"><li>บทความทั้งหมด</li></a>
                <a class="nav-text" href="{% url 'doctors:package' %}"><li>แพ็คเกจ</li></a>
                <a class="nav-text" href="{% url 'doctors:news' %}"><li>ข่าวสาร</li></a>
                <a class="nav-text" href="{% url 'doctors:maps' %}"><li>แผนที่</li></a>
                <a class="nav-text" href="{% url 'doctors:spec' %}"><li>รายชื่อแพทย์</li></a>
                {% endif %}
        </div>
        </ul>
    </nav>

    {% if request.user.is_active %}

    <div class="more-options" id="more-options">
        <a href= "{% url 'doctors:profile' %}" class="more-profile-item">
            <img src=" {{request.user.patient.profile_pic.url}}">
            <div class="profile-detail">
                <h3>{{request.user.patient.First_name}} {{request.user.patient.Last_name}}</h3>
                <p>ดูโปรไฟล์ของคุณ</p>
            </div>
        </a>

        <hr />

        <a href = "{% url 'doctors:logout' %}" class="more-item">
            <div class="normal-a">
                <ion-icon name="log-out-outline"></ion-icon>
            </div>
            <div class="item-detail">
                <p>ออกจากระบบ</p>
            </div>
        </a>
    </div>
    {% endif %}

    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    <script type="text/javascript" src="{% static 'js/app-navbar.js' %}"></script>
    </body>

</html>

doctors/templates/doctors/requirement.html
{% extends "doctors/layout.html" %}
{% load static %}

{% block content %}
    <iframe src="{% static 'pdf/project_requirement.pdf' %}" style="width: 100%;height: 100%;border: none;"></iframe>
{% endblock %}

doctors/templates/doctors/spec.html
{% extends "doctors/layout.html" %}
{% load static %}

{% block head %}
    <link rel="Stylesheet" href="{% static 'css/style-mhor.css' %}">
{% endblock %}

{% block content %}
<div class="header-mhor-menu">
    <div class="group-l">
        <h2>รายชื่อแพทย์ตามสาขา</h2>
        <a href="{% url 'doctors:finddoc' %}" class="no-dec"><h4>ค้นหาแพทย์จากชื่อ</h4></a>
    </div>

    <div class="group-r">
        {% if request.user.is_superuser %}
        <a href="{% url 'doctors:mappointment' %}"><h3>ประวัติการนัดพบแพทย์</h3></a>
        <a href="{% url 'doctors:addDoc' %}"><h3>เพิ่ม</h3></a>
        {% endif %}
    </div>
</div>

<p class="bold">อายุรศาสตร์ทั่วไป</p>
<div class="mhor-card-area-all">
    {% for doctor in list1 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

<p class="bold">ศัลยแพทย์ออร์โธปิดิกส์</p>
<div class="mhor-card-area-all">
    {% for doctor in list2 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

<p class="bold">จักษุแพทย์</p>
<div class="mhor-card-area-all">
    {% for doctor in list3 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

<p class="bold">จิตแพทย์'</p>
<div class="mhor-card-area-all">
    {% for doctor in list4 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}

</div>
<p class="bold">ทันตแพทย์</p>
<div class="mhor-card-area-all">
    {% for doctor in list6 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

<p class="bold">สูตินรีแพทย์</p>
<div class="mhor-card-area-all">
    {% for doctor in list5 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

<p class="bold">กุมารแพทย์</p>
<div class="mhor-card-area-all">
    {% for doctor in list7 %}
    <div class="mhor-card">
        <img src="{{doctor.profile_pic.url}}">
        <div class="news-topic">
            <h3>{{doctor.First_name}} {{doctor.Last_name}}</h3>
        </div>
        <div class="details">
            <p class="bold">ความเชี่ยวชาญ</p>
            <p>{{doctor.spec}}</p>
        </div>
        <a href="{% url 'doctors:docprofile' doctor.id %}" class="read-more">ข้อมูลแพทย์</a>
    </div>
    {% endfor %}
</div>

{% endblock %}